scrape_configs:
  - job_name: 'subscription-managementMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['34.143.166.153:80']

        labels:
          application: 'subscription-management'